language: python
sudo: false
before_script:
- pip install tox
- pip install -U requests"$REQUESTS_VERSION"

# test script
script:  tox
notifications:
  on_success: change
  on_failure: always

env:
  matrix:
  # With latest requests
  - TOXENV=py26 REQUESTS_VERSION=""
  - TOXENV=py27 REQUESTS_VERSION=""
  - TOXENV=py32 REQUESTS_VERSION=""
  - TOXENV=py33 REQUESTS_VERSION=""
  - TOXENV=py34 REQUESTS_VERSION=""
  - TOXENV=pypy REQUESTS_VERSION=""
  # With requests 2.2.1
  - TOXENV=py26 REQUESTS_VERSION="==2.2.1"
  - TOXENV=py27 REQUESTS_VERSION="==2.2.1"
  - TOXENV=py32 REQUESTS_VERSION="==2.2.1"
  - TOXENV=py33 REQUESTS_VERSION="==2.2.1"
  - TOXENV=py34 REQUESTS_VERSION="==2.2.1"
  - TOXENV=pypy REQUESTS_VERSION="==2.2.1"
  # With requets 2.1.0
  - TOXENV=py26 REQUESTS_VERSION="==2.1.0"
  - TOXENV=py27 REQUESTS_VERSION="==2.1.0"
  - TOXENV=py32 REQUESTS_VERSION="==2.1.0"
  - TOXENV=py33 REQUESTS_VERSION="==2.1.0"
  - TOXENV=py34 REQUESTS_VERSION="==2.1.0"
  - TOXENV=pypy REQUESTS_VERSION="==2.1.0"
  - TOXENV=py27-flake8
  - TOXENV=py34-flake8
  - TOXENV=docstrings

matrix:
  allow_failures:
  - env: TOXENV=docstrings
